### ISSUE TITLE
Please publish master branch to crates.io

### ISSUE THREAD

**Issue by JinwooYang** [bryal/dxgi-rs#2]
Hi @bryal. thanks for the great package.

When i import this package using Cargo.toml like this.

```toml
dxgi-win = "0.2.1"
```

It's failed to build.

![image](https://user-images.githubusercontent.com/12711457/67399343-10d29f00-f5e7-11e9-88e6-b0684f1c6e28.png)

I think the problem is the winapi version on the crates.io. it is "*". it should be the "0.2"

Please publish latest source code to crates.io to fix this error.

**Comment by bryal** [comment]
Thanks for the appreciation, but I have no intentions on maintaining this crate any longer. I suppose I should make that clear in the README. The winapi crate does most if not all that this crate does and much more, and is actually up to date and maintained. Please use that instead!

**Comment by JinwooYang** [comment]
Actually, I want to use captrs crate and it's failed to build because of this error. Is captrs no longer maintaining too? If so, I can just fork this crate and fix it for myself.

**Comment by bryal** [comment]
I haven't needed to compile it for quite some time, but I am indeed still using captrs, and I suppose I do want to keep it working.

I'll try getting captrs to build on current rust with winapi instead of this lib today, I think.

**Comment by JinwooYang** [comment]
Thanks! I hope I can use captrs in the near future. :+1:

**Comment by bryal** [comment]
I've now updated `dxgcap`, which `captrs` depends on, to not use `dxgi-win` and `d3d11-win` anymore. Instead, `winapi` is used for most of what those libs previously did, and the `wio` crate is used for the smart pointer `ComPtr`.

I use `captrs` as a dependency in `helion`, and it builds and works just fine now, so please go ahead and try `captrs` out!

**Comment by JinwooYang** [comment]
Nice work! I'll try it. Thank you!
